from cmb.embeddings.cnn_embedding import BmodeCNNEmbedding, BmodeCNNEmbedding128
from cmb.embeddings.mlp_embedding import PlanckLiteMLPEmbedding, PlanckLiteMLPEmbeddingV2
from cmb.embeddings.cnn1d_embedding import PlanckLiteCNN1DEmbedding, PlanckLiteCNN1DEmbeddingV2
from cmb.embeddings.resmlp_embedding import PlanckLiteResMLPEmbedding
